/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import NN.Runtime.Autograd.Engine.Core.Base
public import NN.Runtime.Autograd.Torch.Core.Types

/-!
# Eager Session State

The tapes and side tables shared by eager operations. Parameters own their CUDA mirrors; the
session owns recorded intermediates. Handle generations separate consecutive forward passes.
-/

public section

namespace Runtime.Autograd.Torch.Internal

open Spec TorchLean
/--
Mutable tapes and side tables for eager execution.

`paramsByLeaf` links parameter leaves to their persistent storage. A reset drops the recording and
advances `refGeneration`, but keeps the owner id, random counter, and backend selections.
-/
structure EagerSession (α : Type) [Storage α] where
  /-- Session options controlling backend/device/kernel behavior. -/
  options : Config
  /-- CPU eager tape used when `Config.device options = .cpu`. -/
  tape : IO.Ref (Runtime.Autograd.Tape α)
  /-- CUDA eager tape used when `Config.device options = .cuda`. -/
  cudaTape : IO.Ref (Runtime.Autograd.Cuda.Tape)
  /-- Map from tape leaf ids to trainable parameter objects. -/
  paramsByLeaf : IO.Ref (Std.HashMap Nat (AnyParam α))
  /-- Non-differentiable integer inputs for dynamic indexing operations. -/
  nats : IO.Ref (Array Nat)
  /-- Number of seeded random tensors generated by this session. -/
  rngCounter : IO.Ref Nat
  /-- Accepted capsules already reported for this session, in first-use order. -/
  selectedBackends : IO.Ref (Array NN.Backend.AcceptedKernel)
  /-- Process-unique owner id for session references. -/
  refOwner : Nat
  /-- Current recording generation for session references. -/
  refGeneration : IO.Ref Nat


end Runtime.Autograd.Torch.Internal
