/-
Copyright (c) 2026 TorchLean contributors
Released under MIT license as described in the file LICENSE.
Authors: TorchLean contributors
-/
module

public import NN.Kernel.Function
public import NN.Kernel.Graph
public import NN.Tensor.Internal.Elab.TensorLiteral -- shake: keep

/-!
# Custom tensor computations

Write an ordinary scalar function and use `f.run input (device := cpu)` or `gpu` to apply it to
a tensor of the same shape. CPU evaluates Lean code; GPU generates CUDA and executes it through
NVRTC. Indexed calculations use `Program.of` with explicit input readers and output shapes.
Programs retain their reference calculation and a checked semantic correspondence proof.

GPU execution supports binary32 and binary64, not arbitrary FloatLib formats. Indexed reads
are checked, branches are lazy and bounded folds preserve their accumulation order. Unsupported
source constructs are rejected. NVIDIA compilation, GPU execution and LibTorch remain external
trust boundaries. Custom-operation gradients are not generated by this frontend.
-/
